version: '3.8'

services:
  nuxtapp:
    image: node:20
    container_name: nuxtjs_container
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_container
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nuxtforum
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

volumes:
  db_data: